version : '3.9'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      # - .dbdata:/var/lib/mysql
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "testPwd"
      MYSQL_DATABASE: transaction
    ports:
      - 3306:3306
    

  backend:
    depends_on:
      - db
    build: .
    command: npm run dev
    tty: true
    ports:
      - 8000:8000
  
    volumes:
      - .:/app
      - /node_modules
    environment:
      HOST: db
      MYSQL_USER: root
      MYSQLDB_ROOT_PASSWORD: testPwd
      name: default
      MYSQL_PORT: 3306
      MYSQLDB_DATABASE: transaction

volumes:
  db:  
